"""
joshkurz.net Architecture Diagrams
Generated by Claude Code for live conference demo.

Run directly:
  python3 .claude/skills/architecture-diagram/scripts/generate_diagrams.py

Or via npm:
  npm run build:diagrams

Output PNGs land in .claude/skills/architecture-diagram/output/ (gitignored).
The npm script then copies them to diagrams/ for version control.
"""

import os
from diagrams import Diagram, Cluster, Edge
from diagrams.aws.database import Dynamodb
from diagrams.aws.compute import Lambda
from diagrams.onprem.client import User
from diagrams.programming.framework import React
from diagrams.programming.language import NodeJS
from diagrams.saas.analytics import Snowflake as Analytics
from diagrams.generic.storage import Storage
from diagrams.generic.compute import Rack

# Output next to this script's skill folder
SKILL_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUTPUT_DIR = os.path.join(SKILL_DIR, "output")
os.makedirs(OUTPUT_DIR, exist_ok=True)

# ─────────────────────────────────────────────────────────────────
# Diagram 1: High-Level System Architecture
# ─────────────────────────────────────────────────────────────────
with Diagram(
    "joshkurz.net – System Architecture",
    filename=os.path.join(OUTPUT_DIR, "system_architecture"),
    outformat="png",
    show=False,
    direction="LR",
    graph_attr={"fontsize": "14", "bgcolor": "white", "pad": "0.5"},
):
    user = User("Browser")

    with Cluster("Vercel (Serverless)"):
        nextjs = React("Next.js 13\nHomepage / Dashboard")
        with Cluster("API Routes"):
            api_random  = NodeJS("/api/random-joke")
            api_ai      = NodeJS("/api/ai-joke")
            api_ratings = NodeJS("/api/ratings")
            api_speak   = NodeJS("/api/speak")
            api_custom  = NodeJS("/api/custom-jokes")

    with Cluster("AWS"):
        ratings_table = Dynamodb("RATINGS_TABLE\ndad-jokes-ratings-prod")
        stats_table   = Dynamodb("STATS_TABLE\ndad-jokes-stats-prod")
        agg_lambda    = Lambda("Stats Aggregator\n(DynamoDB Streams)")

    with Cluster("OpenAI"):
        openai_text  = Rack("GPT-4.1\n(joke gen + moderation)")
        openai_audio = Rack("gpt-4o-mini-tts\n(text-to-speech)")

    static_data = Storage("fatherhood_jokes.json\n(500+ jokes)")
    analytics   = Analytics("Google Analytics\n+ Vercel Analytics")

    user >> nextjs
    user >> Edge(label="XHR") >> api_random
    user >> Edge(label="XHR") >> api_ai
    user >> Edge(label="XHR") >> api_ratings
    user >> Edge(label="XHR") >> api_speak
    user >> Edge(label="XHR") >> api_custom

    api_random  >> static_data
    api_ai      >> openai_text
    api_ai      >> ratings_table
    api_ratings >> ratings_table
    api_ratings >> stats_table
    api_speak   >> openai_audio
    api_custom  >> openai_text
    api_custom  >> ratings_table

    ratings_table >> Edge(label="Streams", style="dashed") >> agg_lambda
    agg_lambda    >> stats_table

    nextjs >> analytics


# ─────────────────────────────────────────────────────────────────
# Diagram 2: API Route Map
# ─────────────────────────────────────────────────────────────────
with Diagram(
    "joshkurz.net – API Route Map",
    filename=os.path.join(OUTPUT_DIR, "api_routes"),
    outformat="png",
    show=False,
    direction="TB",
    graph_attr={"fontsize": "13", "bgcolor": "white", "pad": "0.5"},
):
    with Cluster("GET /api/random-joke"):
        rj_handler = NodeJS("handler")
        rj_lib     = NodeJS("lib/jokesData\ngetRandomJokeAsync()")
        rj_src1    = Storage("fatherhood_jokes.json")
        rj_src2    = Dynamodb("Custom Jokes\n(DynamoDB GSI1)")
        rj_handler >> rj_lib >> [rj_src1, rj_src2]

    with Cluster("POST /api/ai-joke"):
        ai_handler  = NodeJS("handler")
        ai_prompt   = NodeJS("lib/aiJokePrompt\nbuildAiJokePrompt()")
        ai_inspire  = NodeJS("lib/jokeInspiration\ntop-rated jokes")
        ai_openai   = Rack("OpenAI GPT-4.1\n(responses.create)")
        ai_persist  = NodeJS("lib/customJokes\nrecordAcceptedJoke()")
        ai_dynamo   = Dynamodb("RATINGS_TABLE\nCUSTOM_JOKE# record")
        ai_handler >> ai_prompt >> ai_inspire >> Dynamodb("STATS_TABLE GSI1")
        ai_prompt >> ai_openai
        ai_handler >> ai_persist >> ai_dynamo

    with Cluster("GET|POST /api/ratings"):
        r_handler = NodeJS("handler")
        r_write   = NodeJS("lib/ratingsStorageDynamo\nwriteRating() O(1)")
        r_read    = NodeJS("lib/ratingsStorageDynamo\nreadStats() O(1)")
        r_rt      = Dynamodb("RATINGS_TABLE\nJOKE# PutItem")
        r_st      = Dynamodb("STATS_TABLE\nSTATS# GetItem")
        r_handler >> r_write >> r_rt
        r_handler >> r_read >> r_st

    with Cluster("GET /api/speak"):
        sp_handler = NodeJS("handler")
        sp_openai  = Rack("OpenAI\ngpt-4o-mini-tts")
        sp_mp3     = Storage("MP3 Stream\n→ browser")
        sp_handler >> sp_openai >> sp_mp3

    with Cluster("POST /api/custom-jokes"):
        cj_handler = NodeJS("handler")
        cj_mod     = Rack("OpenAI moderation\n(GPT-4.1)")
        cj_accept  = NodeJS("recordAcceptedJoke()")
        cj_reject  = NodeJS("recordRejectedJoke()")
        cj_dynamo  = Dynamodb("RATINGS_TABLE")
        cj_handler >> cj_mod
        cj_mod >> Edge(label="accepted") >> cj_accept >> cj_dynamo
        cj_mod >> Edge(label="rejected") >> cj_reject >> cj_dynamo


# ─────────────────────────────────────────────────────────────────
# Diagram 3: AI Joke Generation – Data Flow
# ─────────────────────────────────────────────────────────────────
with Diagram(
    "joshkurz.net – AI Joke Generation Flow",
    filename=os.path.join(OUTPUT_DIR, "ai_joke_flow"),
    outformat="png",
    show=False,
    direction="LR",
    graph_attr={"fontsize": "14", "bgcolor": "white", "pad": "0.6"},
):
    user = User("User\nclicks Generate")

    with Cluster("Next.js Frontend"):
        ui = React("Homepage\n(class component)")

    with Cluster("Vercel Serverless"):
        api = NodeJS("POST /api/ai-joke")

        with Cluster("Prompt Engineering"):
            prompt_builder = NodeJS("buildAiJokePrompt()\nv2 template system")
            inspiration    = NodeJS("jokeInspiration.mjs\ntop-rated examples")

        with Cluster("OpenAI Client"):
            client   = NodeJS("openaiClient.js\nmodel fallback logic")
            primary  = Rack("GPT-4.1\n(primary)")
            fallback = Rack("GPT-4.1\n(fallback)")

        with Cluster("Persistence"):
            custom_lib = NodeJS("customJokes.js\nrecordAcceptedJoke()")

    stats_db   = Dynamodb("STATS_TABLE\nTop Performers (GSI1)")
    ratings_db = Dynamodb("RATINGS_TABLE\nCUSTOM_JOKE# record")

    user >> ui >> Edge(label="POST") >> api
    api >> prompt_builder
    prompt_builder >> inspiration >> stats_db
    prompt_builder >> client
    client >> primary
    client >> Edge(label="on error", style="dashed") >> fallback
    api >> custom_lib >> ratings_db
    api >> Edge(label="JSON response\n{setup, punchline, metadata}") >> ui


print("✓ Diagrams generated:")
print(f"  {OUTPUT_DIR}/system_architecture.png")
print(f"  {OUTPUT_DIR}/api_routes.png")
print(f"  {OUTPUT_DIR}/ai_joke_flow.png")
