import Head from 'next/head'
import Link from 'next/link'
import PropTypes from 'prop-types'
import Header from '../components/Header'
import styles from '../styles/CommunityJokes.module.css'
import { getCustomJokesAsync } from '../lib/customJokes'
import { getAuthorStats } from '../lib/ratingsStorageDynamo'
import { parseAiAuthorSignature, resolveDisplayAuthor } from '../lib/aiJokeNicknames'
import { buildOgImageUrl } from '../lib/ogImage'

const navLinks = [
  { href: '/', label: 'Live Jokes' },
  { href: '/best-dad-jokes', label: 'Top Jokes' },
  { href: '/community-jokes', label: 'AI vs Human' },
  { href: '/dashboard', label: 'Dashboard' },
  { href: '/about', label: 'About' },
  { href: '/games', label: 'Games' },
]

const CANONICAL_URL = 'https://joshkurz.net/community-jokes'
const MIN_VOTES_FOR_VERDICT = 20

// Buckets per-author aggregate stats into "AI-generated" vs "everything else"
// (curated sources like fatherhood.gov/icanhazdadjoke/reddit plus individual
// community submitters all count as human-written).
function splitAiVsHuman(authors) {
  const ai = { totalRatings: 0, totalScore: 0 }
  const human = { totalRatings: 0, totalScore: 0 }
  for (const entry of authors) {
    const bucket = parseAiAuthorSignature(entry.author) ? ai : human
    bucket.totalRatings += entry.totalRatings
    bucket.totalScore += entry.average * entry.totalRatings
  }
  const finalize = (bucket) => ({
    totalRatings: bucket.totalRatings,
    average: bucket.totalRatings > 0 ? Number((bucket.totalScore / bucket.totalRatings).toFixed(2)) : 0,
  })
  return { ai: finalize(ai), human: finalize(human) }
}

function buildVerdict(ai, human) {
  if (ai.totalRatings < MIN_VOTES_FOR_VERDICT || human.totalRatings < MIN_VOTES_FOR_VERDICT) {
    return 'Not enough votes yet to call it — go rate some jokes and help settle the debate.'
  }
  const diff = human.average - ai.average
  if (Math.abs(diff) < 0.05) {
    return `Dead heat — AI and human jokes are rated within a rounding error of each other (${human.totalRatings + ai.totalRatings} votes total).`
  }
  if (diff > 0) {
    return `Humans win — human-written jokes are rated ${diff.toFixed(2)} stars higher on average, across ${human.totalRatings + ai.totalRatings} total votes.`
  }
  return `AI wins — AI-generated jokes are actually rated ${Math.abs(diff).toFixed(2)} stars higher on average, across ${human.totalRatings + ai.totalRatings} total votes.`
}

function JokeCard({ joke, displayAuthor }) {
  return (
    <article className={styles.jokeCard}>
      <p className={styles.jokeOpener}>{joke.opener}</p>
      {joke.response && <p className={styles.jokeResponse}>{joke.response}</p>}
      <div className={styles.jokeMeta}>
        {displayAuthor && <span className={styles.authorPill}>{displayAuthor}</span>}
        <Link href={`/joke/${joke.id}`} className={styles.shareLink}>
          Rate this joke →
        </Link>
      </div>
    </article>
  )
}

JokeCard.propTypes = {
  joke: PropTypes.shape({
    id: PropTypes.string.isRequired,
    opener: PropTypes.string.isRequired,
    response: PropTypes.string,
  }).isRequired,
  displayAuthor: PropTypes.string,
}

export default function CommunityJokes({ aiJokes, communityJokes, aiStats, humanStats }) {
  const total = aiJokes.length + communityJokes.length
  const title = 'AI vs. Human Dad Jokes — Community & AI-Generated'
  const description = `${communityJokes.length} dad jokes written by real people and ${aiJokes.length} generated by AI, rated head-to-head by the community. ${buildVerdict(aiStats, humanStats)}`
  const verdict = buildVerdict(aiStats, humanStats)
  const ogImage = buildOgImageUrl({
    title: 'AI vs. Human Dad Jokes',
    subtitle: verdict,
    badge: 'AI vs Human',
    emoji: '🤖',
  })

  const structuredData = total > 0 ? {
    '@context': 'https://schema.org',
    '@type': 'ItemList',
    name: title,
    description,
    url: CANONICAL_URL,
    numberOfItems: total,
    itemListElement: [...communityJokes, ...aiJokes].slice(0, 10).map((j, i) => ({
      '@type': 'ListItem',
      position: i + 1,
      item: {
        '@type': 'CreativeWork',
        name: j.opener ? j.opener.slice(0, 100) : `Joke #${i + 1}`,
        description: j.response || j.opener || '',
      },
    })),
  } : null

  return (
    <div className={styles.container}>
      <Head>
        <title>{title} | JoshKurz.net</title>
        <meta name="description" content={description} />
        <link rel="canonical" href={CANONICAL_URL} />
        <meta property="og:type" content="website" />
        <meta property="og:url" content={CANONICAL_URL} />
        <meta property="og:title" content={title} />
        <meta property="og:description" content={description} />
        <meta property="og:site_name" content="JoshKurz.net Dad Jokes" />
        <meta property="og:image" content={ogImage} />
        <meta property="og:image:width" content="1200" />
        <meta property="og:image:height" content="630" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:image" content={ogImage} />
        <meta name="twitter:title" content={title} />
        <meta name="twitter:description" content={description} />
        {structuredData && (
          <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }} />
        )}
      </Head>

      <Header navLinks={navLinks} />

      <main className={styles.main}>
        <section className={styles.hero}>
          <h1>AI vs. Human Dad Jokes</h1>
          <p className={styles.heroSubtitle}>
            {communityJokes.length} jokes written by real people, {aiJokes.length} generated by AI —
            all original to this site, rated by the community. Is AI actually funny? Let&apos;s find out.
          </p>
        </section>

        <section className={styles.statsSection}>
          <h2>Is AI Actually Funny?</h2>
          <div className={styles.statsRow}>
            <div className={styles.statCard}>
              <span className={styles.statEmoji}>🤖</span>
              <span className={styles.statLabel}>AI-Generated</span>
              <span className={styles.statAverage}>{aiStats.totalRatings > 0 ? aiStats.average.toFixed(2) : '—'} ★</span>
              <span className={styles.statVotes}>{aiStats.totalRatings.toLocaleString()} votes</span>
            </div>
            <span className={styles.statVs}>vs</span>
            <div className={styles.statCard}>
              <span className={styles.statEmoji}>🧑‍🤝‍🧑</span>
              <span className={styles.statLabel}>Human-Written</span>
              <span className={styles.statAverage}>{humanStats.totalRatings > 0 ? humanStats.average.toFixed(2) : '—'} ★</span>
              <span className={styles.statVotes}>{humanStats.totalRatings.toLocaleString()} votes</span>
            </div>
          </div>
          <p className={styles.statsVerdict}>{verdict}</p>
        </section>

        <section className={styles.section}>
          <div className={styles.sectionHeading}>
            <h2>🧑‍🤝‍🧑 Community Submitted</h2>
            <span className={styles.sectionCount}>{communityJokes.length} jokes</span>
          </div>
          {communityJokes.length === 0 ? (
            <div className={styles.emptyState}>
              <p>No community jokes yet — be the first to submit one!</p>
              <Link href="/submit" className={styles.ctaButton}>Submit a Joke</Link>
            </div>
          ) : (
            <div className={styles.jokeList}>
              {communityJokes.map((joke) => (
                <JokeCard key={joke.id} joke={joke} displayAuthor={joke.author} />
              ))}
            </div>
          )}
        </section>

        <section className={styles.section}>
          <div className={styles.sectionHeading}>
            <h2>🤖 AI-Generated</h2>
            <span className={styles.sectionCount}>{aiJokes.length} jokes</span>
          </div>
          {aiJokes.length === 0 ? (
            <div className={styles.emptyState}>
              <p>No AI-generated jokes saved yet — hit &ldquo;Feeling Groany?&rdquo; on the homepage!</p>
              <Link href="/" className={styles.ctaButton}>Generate One</Link>
            </div>
          ) : (
            <div className={styles.jokeList}>
              {aiJokes.map((joke) => (
                <JokeCard key={joke.id} joke={joke} displayAuthor={resolveDisplayAuthor(joke.author)} />
              ))}
            </div>
          )}
        </section>

        <div className={styles.cta}>
          <p>Think your jokes can beat the robots? Submit one, or vote on the ones above.</p>
          <Link href="/submit" className={styles.ctaButton}>Submit Your Joke</Link>
        </div>
      </main>
    </div>
  )
}

CommunityJokes.propTypes = {
  aiJokes: PropTypes.arrayOf(PropTypes.shape({
    id: PropTypes.string.isRequired,
    opener: PropTypes.string.isRequired,
    response: PropTypes.string,
    author: PropTypes.string,
  })).isRequired,
  communityJokes: PropTypes.arrayOf(PropTypes.shape({
    id: PropTypes.string.isRequired,
    opener: PropTypes.string.isRequired,
    response: PropTypes.string,
    author: PropTypes.string,
  })).isRequired,
  aiStats: PropTypes.shape({
    totalRatings: PropTypes.number.isRequired,
    average: PropTypes.number.isRequired,
  }).isRequired,
  humanStats: PropTypes.shape({
    totalRatings: PropTypes.number.isRequired,
    average: PropTypes.number.isRequired,
  }).isRequired,
}

export async function getServerSideProps() {
  try {
    const [customJokes, authorStats] = await Promise.all([
      getCustomJokesAsync(),
      getAuthorStats(),
    ])

    const aiJokes = customJokes.filter((j) => parseAiAuthorSignature(j.author))
    const communityJokes = customJokes.filter((j) => !parseAiAuthorSignature(j.author))
    const { ai, human } = splitAiVsHuman(authorStats)

    return {
      props: {
        aiJokes,
        communityJokes,
        aiStats: ai,
        humanStats: human,
      },
    }
  } catch {
    return {
      props: {
        aiJokes: [],
        communityJokes: [],
        aiStats: { totalRatings: 0, average: 0 },
        humanStats: { totalRatings: 0, average: 0 },
      },
    }
  }
}
